version: '3.8'

services:
  bge-m3:
    image: llama-server-cuda:11.8.0-22.04
    container_name: bge-m3
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:8080"
    volumes:
      - ${MODELS_VOLUME}
    environment:
      - MODEL_PATH=${BGE_M3_MODEL_PATH}
      - LLAMA_ARG_N_GPU_LAYERS=99
      - LLAMA_ARG_CTX_SIZE=4096
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=8080
      - LLAMA_API_KEY=${API_KEY:-your_secret_key}
#      - CTX_SIZE=${CTX_SIZE_4K}
#      - API_KEY=${API_KEY}
    command:
      - -m
      - ${MODEL_PATH}
#      - -ngl
#      - "${NGL}"
#      - -c
#      - "${CTX_SIZE}"
#      - --host
#      - 0.0.0.0
#      - --port
#      - "8080"
#      - --api-key
#      - "${API_KEY}"
      - --embedding

  bge-reranker-v2-m3:
    image: llama-server-cuda:11.8.0-22.04
    container_name: bge-reranker-v2-m3
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8081:8080"
    volumes:
      - ${MODELS_VOLUME}
    environment:
      - MODEL_PATH=${BGE_RERANKER_MODEL_PATH}
      - NGL=${NGL_99}
      - CTX_SIZE=${CTX_SIZE_4K}
      - API_KEY=${API_KEY}
      - UBATCH_SIZE=${UBATCH_SIZE}
      - BATCH_SIZE=${BATCH_SIZE}
    command:
      - -m
      - ${MODEL_PATH}
      - -ngl
      - "${NGL}"
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --api-key
      - "${API_KEY}"
      - -c
      - "${CTX_SIZE}"
      - --ubatch-size
      - "${UBATCH_SIZE}"
      - --batch-size
      - "${BATCH_SIZE}"
      - -np
      - "1"
      - --rerank
      - --embedding
      - --pooling
      - rank

  llama-31-8b-q6k:
    image: llama-server-cuda:11.8.0-22.04
    container_name: llama-31-8b-q6k
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8090:8080"
    volumes:
      - ${MODELS_VOLUME}
    environment:
      - MODEL_PATH=${LLAMA_31_8B_MODEL_PATH}
      - NGL=${NGL_99}
      - CTX_SIZE=${CTX_SIZE_8K}
      - API_KEY=${LLAMA_API_KEY}
    command:
      - -m
      - ${MODEL_PATH}
      - -ngl
      - "${NGL}"
      - -c
      - "${CTX_SIZE}"
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --api-key
      - "${API_KEY}"
